// Copyright (c) 2026, tsubasamusu All rights reserved.

#include "Setting/TsubasamusuSettingsCustomization.h"
#include "DetailLayoutBuilder.h"
#include "DetailWidgetRow.h"
#include "Setting/SLanguageComboButton.h"
#include "Widgets/Layout/SBox.h"
#include "Widgets/Input/SButton.h"
#include "Widgets/Input/SEditableTextBox.h"
#include "Widgets/Text/STextBlock.h"
#include "Widgets/Images/SImage.h"
#include "IDocumentation.h"
#include "TsubasamusuEditorSettingsUtility.h"
#include "TsubasamusuUnrealAssistSettings.h"

#define LOCTEXT_NAMESPACE "TsubasamusuUnrealAssist"

TSharedRef<IDetailCustomization> FTsubasamusuSettingsCustomization::Create()
{
    return MakeShared<FTsubasamusuSettingsCustomization>();
}

void FTsubasamusuSettingsCustomization::CustomizeDetails(IDetailLayoutBuilder& DetailBuilder)
{
	ChangePropertyDisplayAsPassword(DetailBuilder, TEXT("Comment Generation"), TEXT("OpenAiApiKey"));
    ChangePropertyDisplayAsPassword(DetailBuilder, TEXT("Comment Translation"), TEXT("DeeplApiKey"));
    
	AddCommentGenerationLanguageProperty(DetailBuilder);
    AddGptModelsDocumentButton(DetailBuilder);
    AddButtonToApplyRecommendedEditorSettings(DetailBuilder);
}

void FTsubasamusuSettingsCustomization::ChangePropertyDisplayAsPassword(IDetailLayoutBuilder& InDetailLayoutBuilder, const FName& CategoryName, const FName& PropertyName)
{
    IDetailCategoryBuilder& DetailCategoryBuilder = InDetailLayoutBuilder.EditCategory(CategoryName);
    
#if (ENGINE_MAJOR_VERSION == 5 && ENGINE_MINOR_VERSION >= 4)
    check(!DetailCategoryBuilder.IsEmpty());
#endif

    TArray<TSharedRef<IPropertyHandle>> PropertyHandles;
    DetailCategoryBuilder.GetDefaultProperties(PropertyHandles);

    for (const TSharedRef<IPropertyHandle>& PropertyHandle : PropertyHandles)
    {
#if (ENGINE_MAJOR_VERSION == 5 && ENGINE_MINOR_VERSION >= 3)
        if (PropertyHandle->GetProperty()->GetName() != PropertyName)
#else
        if (PropertyHandle->GetProperty()->GetName() != PropertyName.ToString())
#endif
        {
            continue;
        }

        DetailCategoryBuilder.AddProperty(PropertyHandle)
        .CustomWidget()
        .NameContent()
        [
            PropertyHandle->CreatePropertyNameWidget()
        ]
        .ValueContent()
        .MinDesiredWidth(250)
        [
            SNew(SHorizontalBox)
            + SHorizontalBox::Slot()
            .FillWidth(1.0f)
            [
                SNew(SEditableTextBox)
                .Text_Lambda([PropertyHandle]()
                {
                    FString Value;
                    PropertyHandle->GetValue(Value);
                    return FText::FromString(Value);
                })
                .OnTextCommitted_Lambda([PropertyHandle](const FText& NewText, ETextCommit::Type)
                {
                    PropertyHandle->SetValue(NewText.ToString());
                })
                .IsPassword(true)
            ]
        ];
    }
}

void FTsubasamusuSettingsCustomization::AddCommentGenerationLanguageProperty(IDetailLayoutBuilder& InDetailLayoutBuilder)
{
    const FName CategoryName = TEXT("Comment Generation");
    const FText CategoryText = LOCTEXT("CommentGenerationCategoryText", "Comment Generation");
    const FText PropertyText = LOCTEXT("CommentGenerationLanguagePropertyText", "Language");
    const FText ToolTipText = LOCTEXT("CommentGenerationLanguageToolTipText", "The language of comments generated by GPT. (This property will become editable if you uncheck \"Use Editor Language.\")");

    IDetailCategoryBuilder& DetailCategoryBuilder = InDetailLayoutBuilder.EditCategory(CategoryName);
    
#if (ENGINE_MAJOR_VERSION == 5 && ENGINE_MINOR_VERSION >= 4)
    check(!DetailCategoryBuilder.IsEmpty());
#endif
    
    TSharedPtr<IPropertyHandle> UseEditorLanguagePropertyHandle = InDetailLayoutBuilder.GetProperty(GET_MEMBER_NAME_CHECKED(UTsubasamusuUnrealAssistSettings, bUseEditorLanguageForCommentGeneration));
    
    if (UseEditorLanguagePropertyHandle.IsValid())
    {
        DetailCategoryBuilder.AddProperty(UseEditorLanguagePropertyHandle);
    }
    
    const TSharedRef<FLocalizedCulturesFlyweight> LocalizedCulturesFlyweight = MakeShared<FLocalizedCulturesFlyweight>();

    DetailCategoryBuilder.AddCustomRow(PropertyText)
    .NameContent()
    [
        SNew(STextBlock)
        .Text(PropertyText)
        .Font(InDetailLayoutBuilder.GetDetailFont())
        .ToolTipText(ToolTipText)
    ]
    .ValueContent()
    [
        SNew(SLanguageComboButton, LocalizedCulturesFlyweight)
        .OnLanguageSelected_Lambda([](const FCulturePtr& SelectedLanguageCulture)
        {
            UTsubasamusuUnrealAssistSettings* TsubasamusuUnrealAssistSettings = FTsubasamusuEditorSettingsUtility::GetSettingsChecked<UTsubasamusuUnrealAssistSettings>();
            TsubasamusuUnrealAssistSettings->SetCommentGenerationLanguageCulture(SelectedLanguageCulture);
        })
        .IsEnabled_Lambda([]()
        {
	        const UTsubasamusuUnrealAssistSettings* TsubasamusuUnrealAssistSettings = FTsubasamusuEditorSettingsUtility::GetSettingsChecked<UTsubasamusuUnrealAssistSettings>();
            return !TsubasamusuUnrealAssistSettings->bUseEditorLanguageForCommentGeneration;
        })
    ];
}

void FTsubasamusuSettingsCustomization::AddGptModelsDocumentButton(IDetailLayoutBuilder& InDetailLayoutBuilder)
{
    const FName CategoryName = TEXT("Comment Generation");
    const FName PropertyName = TEXT("GptModelName");
    const FText HintText = LOCTEXT("GptModelsDocumentButtonHintText", "gpt-4o-mini");
    const FText ToolTipText = LOCTEXT("GptModelsDocumentButtonToolTipText", "View the types of GPT models currently available");
    const FString GptModelsDocumentUrl = TEXT("https://platform.openai.com/docs/models");

    IDetailCategoryBuilder& DetailCategoryBuilder = InDetailLayoutBuilder.EditCategory(CategoryName);
    
#if (ENGINE_MAJOR_VERSION == 5 && ENGINE_MINOR_VERSION >= 4)
    check(!DetailCategoryBuilder.IsEmpty());
#endif

    TArray<TSharedRef<IPropertyHandle>> PropertyHandles;
    DetailCategoryBuilder.GetDefaultProperties(PropertyHandles);

    for (const TSharedRef<IPropertyHandle>& PropertyHandle : PropertyHandles)
    {
#if (ENGINE_MAJOR_VERSION == 5 && ENGINE_MINOR_VERSION >= 3)
        if (PropertyHandle->GetProperty()->GetName() != PropertyName)
#else
        if (PropertyHandle->GetProperty()->GetName() != PropertyName.ToString())
#endif
        {
            continue;
        }

        DetailCategoryBuilder.AddProperty(PropertyHandle)
        .CustomWidget()
        .NameContent()
        [
            PropertyHandle->CreatePropertyNameWidget()
        ]
        .ValueContent()
        .MinDesiredWidth(200.f)
        [
            SNew(SHorizontalBox)
            + SHorizontalBox::Slot()
            .AutoWidth()
            [
                SNew(SEditableTextBox)
                .Font(FAppStyle::GetFontStyle("PropertyWindow.NormalFont"))
                .HintText(HintText)
                .Text_Lambda([PropertyHandle]()
                {
                    FString Value;
                    PropertyHandle->GetValue(Value);
                    return FText::FromString(Value);
                })
                .OnTextCommitted_Lambda([PropertyHandle](const FText& NewText, ETextCommit::Type)
                {
                    PropertyHandle->SetValue(NewText.ToString());
                })
            ]
            + SHorizontalBox::Slot()
            .AutoWidth()
            .Padding(5.f, 0.f, 0.f, 0.f)
            [
                SNew(SButton)
                .ButtonStyle(FAppStyle::Get(), TEXT("NoBorder"))
                .ButtonColorAndOpacity(FLinearColor::White)
                .ToolTipText(ToolTipText)
                .OnClicked_Lambda([GptModelsDocumentUrl]()
                {
                    // ReSharper disable once CppExpressionWithoutSideEffects
                    IDocumentation::Get()->Open(GptModelsDocumentUrl);
                    return FReply::Handled();
                })
                [
                    SNew(SBox)
                    .HAlign(HAlign_Fill)
                    .VAlign(VAlign_Fill)
                    [
                        SNew(SImage)
                        .ColorAndOpacity(FLinearColor::White)
                        .Image(FAppStyle::Get().GetBrush(TEXT("MainFrame.VisitSearchForAnswersPage")))
                    ]
                ]
            ]
        ];
    }
}

void FTsubasamusuSettingsCustomization::AddButtonToApplyRecommendedEditorSettings(IDetailLayoutBuilder& InDetailLayoutBuilder)
{
    const FName CategoryName = TEXT("General");
    const FText PropertyText = LOCTEXT("ApplyRecommendedEditorSettingsButtonPropertyText", "Apply Recommended Editor Settings");
    const FText ButtonText = LOCTEXT("ApplyRecommendedEditorSettingsButtonText", "Apply");
    const FText ToolTipText = LOCTEXT("ApplyRecommendedEditorSettingsButtonToolTipText",
        "Apply the editor settings recommended by this plugin’s developer. Specifically, as follows:\n\n"
        "- Disable auto save.\n"
        "- Do not restore the tabs of assets that were open previously when the editor is restarted.\n"
        "- Set the location where asset editors open to “Main Window.”\n"
        "- Make comment bubble visible when zooming out in the Event Graph.\n"
        "- Set the default color of comment nodes to black.\n"
        "- Set the editor language to English.\n"
        "- Also use English for node names, pin names, and property names.\n"
        "- Prevent nodes that are placed in a “ghost” state by default, such as BeginPlay and Tick, from being placed by default. (So that no “ghost” nodes exist when creating a Blueprint.)\n"
        "- Make Cast nodes appear as Pure by default, with no execution pins.\n"
        "- Display the Output Log in color.\n"
        "- Make the toolbar icons display more compactly.\n"  
        "- When starting PIE, automatically focus the viewport even if it hasn’t been clicked."
    );
    
    IDetailCategoryBuilder& DetailCategoryBuilder = InDetailLayoutBuilder.EditCategory(CategoryName);
    
#if (ENGINE_MAJOR_VERSION == 5 && ENGINE_MINOR_VERSION >= 4)
    check(!DetailCategoryBuilder.IsEmpty());
#endif
    
    DetailCategoryBuilder.AddCustomRow(PropertyText)
    .NameContent()
    [
        SNew(STextBlock)
        .Text(PropertyText)
        .Font(InDetailLayoutBuilder.GetDetailFont())
        .ToolTipText(ToolTipText)
    ]
    .ValueContent()
    [
        SNew(SVerticalBox)
        + SVerticalBox::Slot()
        [
            SNew(SButton)
            .Text(ButtonText)
            .HAlign(HAlign_Center)
            .ToolTipText(ToolTipText)
            .OnClicked_Lambda([]()
            {
                FTsubasamusuEditorSettingsUtility::ChangeEditorSettingsForTsubasamusu();
                return FReply::Handled();
            })
        ]
    ];
}

#undef LOCTEXT_NAMESPACE
