// Copyright (c) 2026, tsubasamusu All rights reserved.

#pragma once

#include "CoreMinimal.h"
#include "LlamaServerOption.h"
#include "LlamaServerOption_Temperature.generated.h"

/* The randomness of responses generated by the LLM. */
UCLASS(DisplayName = "Temperature")
class ULlamaServerOption_Temperature : public ULlamaServerOption
{
	GENERATED_BODY()
	
public:
	//~ Begin ULlamaServerOption Interface
	virtual FString GetParameter() const override;
	
	virtual void SetArgument(const FString& InArgument) override;
	virtual FString GetArgument(const bool bForConfig = false) const override;
	
	virtual bool IsValidArgument() const override;
	//~ End ULlamaServerOption Interface
	
private:
	/* The randomness of responses generated by the LLM. */
	UPROPERTY(EditAnywhere, meta = (ClampMin = "0.0", ClampMax = "1.0"))
	float Temperature = 0.8f;
};
