// Copyright (c) 2026, tsubasamusu All rights reserved.

#pragma once

#include "CoreMinimal.h"
#include "Type/TsubasamusuUnrealAssistEnums.h"
#include "LlamaServerOption.generated.h"

UCLASS(EditInlineNew, CollapseCategories, Abstract)
class ULlamaServerOption : public UObject
{
	GENERATED_BODY()
	
public:
	virtual FString GetParameter() const PURE_VIRTUAL(ULlamaServerOption::GetParameter, return FString(););
	
	virtual void SetArgument(const FString& InArgument) PURE_VIRTUAL(ULlamaServerOption::SetArgument, );
	virtual FString GetArgument(const bool bForCommandLineArguments = false) const PURE_VIRTUAL(ULlamaServerOption::GetArgument, return FString(););
	
	virtual bool IsValidArgument() const PURE_VIRTUAL(ULlamaServerOption::IsValidArgument, return false;);
	
	virtual bool IsLongParameter() const { return true; };
};

/* LLM file path to load. */
UCLASS(DisplayName = "Model")
class ULlamaServerOption_Model : public ULlamaServerOption
{
	GENERATED_BODY()
	
public:
	//~ Begin ULlamaServerOption Interface
	virtual FString GetParameter() const override;
	
	virtual void SetArgument(const FString& InArgument) override;
	virtual FString GetArgument(const bool bForCommandLineArguments = false) const override;
	
	virtual bool IsValidArgument() const override;
	//~ End ULlamaServerOption Interface
	
private:
	/* LLM file path to load. */
	UPROPERTY(EditAnywhere, meta = (DisplayName = "LLM File Path", FilePathFilter = "gguf"))
	FFilePath LlmFilePath;
};

/* The port number for the Llama server. */
UCLASS(DisplayName = "Port")
class ULlamaServerOption_Port : public ULlamaServerOption
{
	GENERATED_BODY()
	
public:
	//~ Begin ULlamaServerOption Interface
	virtual FString GetParameter() const override;
	
	virtual void SetArgument(const FString& InArgument) override;
	virtual FString GetArgument(const bool bForCommandLineArguments = false) const override;
	
	virtual bool IsValidArgument() const override;
	//~ End ULlamaServerOption Interface
	
private:
	/* The port number for the Llama server. */
	UPROPERTY(EditAnywhere, meta = (ClampMin = "1024", ClampMax = "65535"))
	int32 LlamaServerPort = 8080;
};

/* The size of the prompt context. If set to 0, the context size is loaded from the model. */
UCLASS(DisplayName = "ContextSize")
class ULlamaServerOption_ContextSize : public ULlamaServerOption
{
	GENERATED_BODY()
	
public:
	//~ Begin ULlamaServerOption Interface
	virtual FString GetParameter() const override;
	
	virtual void SetArgument(const FString& InArgument) override;
	virtual FString GetArgument(const bool bForCommandLineArguments = false) const override;
	
	virtual bool IsValidArgument() const override;
	//~ End ULlamaServerOption Interface
	
private:
	/* The size of the prompt context. If set to 0, the context size is loaded from the model. */
	UPROPERTY(EditAnywhere, meta = (ClampMin = "0"))
	int32 ContextSize = 0;
};

/* The number of CPU threads to use during generation. */
UCLASS(DisplayName = "Threads")
class ULlamaServerOption_Threads : public ULlamaServerOption
{
	GENERATED_BODY()
	
public:
	//~ Begin ULlamaServerOption Interface
	virtual FString GetParameter() const override;
	
	virtual void SetArgument(const FString& InArgument) override;
	virtual FString GetArgument(const bool bForCommandLineArguments = false) const override;
	
	virtual bool IsValidArgument() const override;
	//~ End ULlamaServerOption Interface
	
private:
	/* The number of CPU threads to use during generation. */
	UPROPERTY(EditAnywhere, meta = (DisplayName = "CPU Threads Number"))
	int32 CpuThreadsNumber = -1;
};

/* Whether to enable the Web UI. */
UCLASS(DisplayName = "Enable Web UI")
class ULlamaServerOption_EnableWebUi : public ULlamaServerOption
{
	GENERATED_BODY()
	
public:
	//~ Begin ULlamaServerOption Interface
	virtual FString GetParameter() const override;
	
	virtual void SetArgument(const FString& InArgument) override;
	virtual FString GetArgument(const bool bForCommandLineArguments = false) const override;
	
	virtual bool IsValidArgument() const override;
	//~ End ULlamaServerOption Interface
	
private:
	/* Whether to enable the Web UI. */
	UPROPERTY(EditAnywhere, meta = (DisplayName = "Enable Web UI"))
	bool bEnableWebUi = false;
};

/* The randomness of responses generated by the LLM. */
UCLASS(DisplayName = "Temperature")
class ULlamaServerOption_Temperature : public ULlamaServerOption
{
	GENERATED_BODY()
	
public:
	//~ Begin ULlamaServerOption Interface
	virtual FString GetParameter() const override;
	
	virtual void SetArgument(const FString& InArgument) override;
	virtual FString GetArgument(const bool bForCommandLineArguments = false) const override;
	
	virtual bool IsValidArgument() const override;
	//~ End ULlamaServerOption Interface
	
private:
	/* The randomness of responses generated by the LLM. */
	UPROPERTY(EditAnywhere, meta = (ClampMin = "0.0", ClampMax = "1.0"))
	float Temperature = 0.8f;
};

/* The number of layers to store in VRAM. */
UCLASS(DisplayName = "GPU Layers")
class ULlamaServerOption_GpuLayers : public ULlamaServerOption
{
	GENERATED_BODY()
	
public:
	//~ Begin UObject Interface
	virtual void PostEditChangeProperty(FPropertyChangedEvent& InPropertyChangedEvent) override;
	//~ End UObject Interface

	//~ Begin ULlamaServerOption Interface
	virtual FString GetParameter() const override;
	
	virtual void SetArgument(const FString& InArgument) override;
	virtual FString GetArgument(const bool bForCommandLineArguments = false) const override;
	
	virtual bool IsValidArgument() const override;
	//~ End ULlamaServerOption Interface
	
private:
	/* The number type of layers to store in VRAM. */
	UPROPERTY(EditAnywhere, meta = (DisplayName = "GPU Layers"))
	EGpuLayers GpuLayers = EGpuLayers::Auto;
	
	/* The number of layers to store in VRAM. */
	UPROPERTY(EditAnywhere, meta = (DisplayName = "GPU Layers Number", ClampMin = "0", EditCondition = "GpuLayers == EGpuLayers::ExactNumber"))
	int32 GpuLayersNumber = 0;
};
